### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by joto** [osmcode/libosmium#33]
There are lots of changes needed for Windows support. Smaller changes can just be added and tracked in this issue, for more complicated changes a new issue should be opened.

Changes in alex85k/libosmium/msvc:
- [X] alex85k@09511beffb9e80fd8bf3d29ab90261a8444fc099 - superseeded
- [X] alex85k@f5c60c65ae3974779ff037d402efc283265e2e08 - merged
- [X] alex85k@7ebd3818541af9b83cc56fa311bf5aff386ea67b - merged
- [X] alex85k@7df90b77affa1a8fc47642db0fbaea7c6497fd07 - merged
- [X] alex85k@ef238bbd134e44f28bb91f9a75de33fd17adf050 - see #35, not merged, superseeded by 1f46a080341bdeeb490b63dcbccdbd1f436a5ccc
- [X] alex85k@c6eb013e5ac2b8a1a321d3df35a7d9b8f4df5852 - see #34, not merged, superseeded by efaffc326bc5d0bd0ac04b901ae98f30ce6db749
- [X] alex85k@59763f60dc1dba145f66e866e04507645cec7300 - not merged, superseeded by d959a9ee07763c6c2c6903ad59313abdf365f512
- [X] alex85k@aba26680c8fcabea3b60a5badf82171af2b5174a - out of date
- [X] alex85k@e76438da7ff219e203785364e29bac60f15a754a - see #34, not merged, superseeded by efaffc326bc5d0bd0ac04b901ae98f30ce6db749
- [X] alex85k@c9518573192490873f3945f6cac791fe930e76b1 - merged
- [X] alex85k@43977320c709012a28feb785b75f52a470682acd - merged
- [X] alex85k@f4b0f821376a281686e1522b4396f6ec9842b49c - not merged, superseeded by ec037bd0cf5d015cd651437dcfa59d02e6cd402c
- [X] alex85k@0cd5f277a3219d3d037d2f666cc8a818684f09a2 - merged
- [X] alex85k@2a9f59aa5c29feda8a2628c5ea10db5cf9f58f4d - merged
- [X] alex85k@00c2504330ed461eebb23b19a7f8de755512e220 - not merged, superseeded by b14222cfd0e6c37789815bf3a7319d1d5e07d2ca
- [X] alex85k@6e430a1db4653b9387242985321a93c6d16c312c - superseeded by alex85k@b39760542dc7544885b684656d5cbd283297f849
- [X] alex85k@4de4e18dfe8a1f8d3208d85a532804a2aac866f1 - merged
- [X] alex85k@9a1f19d9dff395882886f7a3d8c1d432377a03f0 - not merged, superseeded by 28c174634e6fda1a0a49fdaa274828ee62ae82f8
- [X] alex85k@2d039c3fba777ccdf4b8fc1d5f74b22489743de0 - fixed with 32b2331bdabc7ab6d34ffbe7e5804f90edcccc14
- [X] alex85k@c64d7560770e9aeed826bacb0f56108d9035cae6 - merged
- [ ] alex85k@b39760542dc7544885b684656d5cbd283297f849 - not merged, will not work like that, see #36
- [X] alex85k@9a34e4312edcc63408b853249696d7e8a9c6de44 - not merged, superseeded by 12bf8ca534fbb35d882f19263480b023ec27e140
- [X] alex85k@3959b2007aebb06990cf75a3efecca7190a9cd9f - merged
- [X] alex85k@88103f5c78e04d80978bce2b6ea431b0a27d8777 - merged
- [X] alex85k@d07f43e8adb441506d1e6a0b35d60f14e271094f - merged as 72844f4d6ff58eaca27562b422fc18d31238656e
- [X] alex85k@6c11293a00c1fd6445ed5fa8eba9a9f6f7414187 - not merged, superseeded by 0f34aa38e47b4b6db19db47509474589e2ac2b24
- [X] alex85k@e8ad20f0d5837ecd8bd5fb14fdeed281ec90f0b6 - not merged, superseeded by 32b2331bdabc7ab6d34ffbe7e5804f90edcccc14
- [X] alex85k@c71b03f0f784afebd68d8b03033934a3c70a81d0 - merged
- [X] alex85k@4190c6d2f513e588d84e241893cc425a9055ef02 - merged (see #39)
- [X] alex85k@5931171f463748befdda961291d15b3d823dd8ca - merged

Other issues concerning windows are labled 'windows'.
